server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: "*"
        
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka    
    
spring:
  application:
    name: CONFIG-SERVER


    
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Amir-Suhel/config-service
          clone-on-start: true  
    



